### ISSUE TITLE
Viability of using minimina for a local testing engine

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#15]
**Problem**
I've heard that local networks tend to crash after a couple hours of operation and may be too resource intensive.

**Assessment Criteria**
Gain confidence in the direction of using minimina as a local testing engine and record metrics.

**Tasks**
- [x] Run minimina on local machine
- [x] Monitor various metrics, e.g. RAM, CPU usage
- [ ] Understand the requirements of a typical test network
- [ ] Run minimina under the load of a typical test network

**Comment by Isaac-DeFrain** [comment]
This would be an invaluable way for devs to test tiers 1 & 2 locally, before merging/running their code on the CI

**Comment by Isaac-DeFrain** [comment]
With a {push, pull}-based `Network_state` utilizing GQL it will be possible to use minimina for local test deployments
