### ISSUE TITLE
Configs vs dune profiles

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#16]
**Problem**
There was a discussion between myself and Michal about potential differences/similarities of building from config vs using optcomp and building from dune profiles.

**Assessment Criteria**
Understand the differences/similarities and pros/cons better and express view in the mf-ci channel.

**Tasks**

- [x] Understand building with optcomp from dune profile
- [x] Understand building from config
- [x] Pros and cons
- [ ] Write a summary in mf-ci channel
