### ISSUE TITLE
Simplify and heavily comment the testing library

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#17]
**Problem**
Writing integration tests requires a lot of knowledge about where commonly used functions live and the amount of deeply nested modules render the testing more opaque then it ought to be.

**Assessment Criteria**
Produce a simplified and streamlined `test_util` module which packages up commonly used testing functionality.

**Tasks**

- [x] Determine what testing functionality is commonly used
- [x] Adds lot of comments to `test_common`
- [x] Update `test_common` to make functionality more accessible
- [x] Rewrite integration tests using the `test_common` functionality

**Comment by Isaac-DeFrain** [comment]
[Commonly used](https://www.notion.so/minafoundation/Test-Executive-Helper-Functions-b55526fd69c643c69e485d35766dc0c0?pvs=4#4ce3abc400004a5d8ecb1d820059c054)

**Comment by Isaac-DeFrain** [comment]
WIP branch with this work https://github.com/MinaFoundation/mina/tree/integration-test-improvements
