### ISSUE TITLE
add ci jobs based on info logged in #28 issue

### ISSUE THREAD

**Issue by simisimis** [MinaFoundation/mina#33]
## Problem
Now that jobs definitions have been collected #28 , we need to implement them on our CI.

## Acceptance Criteria
Jobs that run on buildkite should be recreated on our CI and successfully complete.

## Tasks
- [ ] Get all Test jobs ported
- [ ] Get all Lint jobs ported
- [ ] Get all release jobs ported
