### ISSUE TITLE
Mock network to test the abstract engine

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#43]
**Problem**

The abstract engine has undergone a lot of changes in past few weeks. In order to test these changes, we need a mock network for the abstract engine to interact with.

**Assessment Criteria**

CLI flags are finalized and command outputs conform to return spec.

**Tasks**

- [x] Copy minimina repo
- [x] Finalize CLI flags
- [x] Finalize output and adjust the return spec
