### ISSUE TITLE
Figure out what's causing Lucy to take 5 mins to deploy a mock network

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#46]
**Problem**

The test executive is taking about 5 mins to deploy even a mock network. We need to get to the bottom of what is causing this.

**Assessment Criteria**

We understand the source of this performance problem and have ideas about how to fix it.

**Tasks**

- [x] Run the `heap_usage` app
- [x] Run flamegraph
- [x] Figure out why Lucy takes so long to spin up a network
- [x] Come up with ideas about how to fix it

**Comment by Isaac-DeFrain** [comment]
My suspicion is that this delay is caused by proof and genesis ledger generation. If that's found to be the case, maybe we can cache proofs and ledgers for the commonly used test network configurations instead of doing the heavy lifting every time.

**Comment by Isaac-DeFrain** [comment]
Flamegraph and the `heap_usage` app may be crucial here

**Comment by Isaac-DeFrain** [comment]
`heap_usage` is more like a benchmarking tool, it does not measure heap usage for arbitrary program executions. However, we could modify it to do that if we deem it worthwhile.

Here's an example execution's output:

```txt
Generated zkapp transactions with 17 updates and 16 proof updates in 37.053484 secs
Generated updates permutation 0: SPPPPPPPPPPPPPPPP
Updating authorizations...
Data of type Account.t (w/ zkapp)                           uses    211 heap words =     1688 bytes
Data of type Zkapp_command.t                                uses  52795 heap words =   422360 bytes
Data of type Pickles.Side_loaded.Proof.t                    uses   3502 heap words =    28016 bytes
Data of type Mina_base.Side_loaded_verification_key.t       uses    890 heap words =     7120 bytes
Data of type Dummy Pickles.Side_loaded.Proof.t              uses   2707 heap words =    21656 bytes
Data of type Dummy Mina_base.Side_loaded_verification_key.t uses     99 heap words =      792 bytes
Data of type Ledger.Db.path.t                               uses    422 heap words =     3376 bytes
Data of type Protocol_state.t                               uses    563 heap words =     4504 bytes
Data of type Pending_coinbase.t                             uses    595 heap words =     4760 bytes
Data of type Staged_ledger_diff.t (payments)                uses    660 heap words =     5280 bytes
Data of type Parallel_scan.Base.t (coinbase)                uses    997 heap words =     7976 bytes
Data of type Parallel_scan.Base.t (payment)                 uses   1092 heap words =     8736 bytes
Data of type Parallel_scan.Base.t (zkApp)                   uses  54811 heap words =   438488 bytes
Data of type Parallel_scan.Merge.t                          uses   8763 heap words =    70104 bytes
Data of type Transaction_snark.Statement.t                  uses    246 heap words =     1968 bytes
```

**Comment by Isaac-DeFrain** [comment]
The cause is network keypair generation for the 1000 dummy accounts in the genesis ledger created by the `Network_config.expand` function

**Comment by Isaac-DeFrain** [comment]
Pre-generated keypairs live here https://github.com/MinaFoundation/lucy-keypairs
