### ISSUE TITLE
Adapt Test_config.t to provide all info for test network configuration

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#55]
**Problem**

`Test_config.t` contains almost all info required by the network runner to generate a test network, but it is missing some things.

**Assessment Criteria**

Implement a way to transform the test config to contain all required info for the network runner.

**Tasks**

- [x] Get a handle on what all is required by the network runner
- [x] Assess what's missing from the test config
- [x] Implement the transformation functions

**Comment by Isaac-DeFrain** [comment]
The intention is to provide separate genesis ledger and topology files to the network runner which are derived from the `Test_config.t` created in the specific test
