### ISSUE TITLE
Minimina - Publish and document beta version on MinaFoudation Dockerhub

### ISSUE THREAD

**Issue by kaozenn** [MinaFoundation/mina#6]
**Problem**
We need to publish the first iteration of minimina in order to get traction and feedback.
Minimina currently lives in our internal ECR.

**Acceptance Criteria**
Users are familiar with minimina.
User are able to spin up a Network locally
User can import one or more accounts with allocated funds
User can perform a transaction between two accounts

**Tasks**
- [x] Create a dockerhub account for the MinaFoundation
- [x] Store dockerhub account credentials on AWS Secret Manager
- [x] Create a Minimina docker repository
- [x] Publish the first iteration of Minimina
- [x] Write getting started documentation

**Comment by kaozenn** [comment]
The URL of the docker repository is

https://hub.docker.com/repository/docker/minafoundation/minimina/general

cc: @halsaphi

**Comment by kaozenn** [comment]
cc: @halsaphi
