### ISSUE TITLE
Build test daemons from specific git commits/tags

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#73]
**Problem**

Currently, daemons used in the network are all the same and must be pulled from a docker image.

**Assessment Criteria**

Provide the ability to build daemons from specific git commits and/or tags.

**Tasks**

- [x] Provide an optional field to specify commit/tag, default to `mina-image` docker image
- [x] Make `docker_image` topology field optional
- [x] Adjust topology types in minimina
- [ ] Implement specific git commit/tag daemon building in minimina
- [ ] Make docker container from local mina branch

**Comment by Isaac-DeFrain** [comment]
Relates to https://github.com/MinaFoundation/mina/issues/76
