### ISSUE TITLE
Create branching model in Minafoundation/mina repository

### ISSUE THREAD

**Issue by kaozenn** [MinaFoundation/mina#8]
**Problem**
See description of the problem statement [here](https://www.notion.so/minafoundation/Branching-f88a07e2373c4916b3adeaccc14b0612?pvs=4#850b637fa4d440d5a55695b4a7fcbb12)

**Acceptance Criteria**
All branches are mapped according the [branching document](https://www.notion.so/minafoundation/Branching-f88a07e2373c4916b3adeaccc14b0612)

**Tasks**
- [x] Create branches in the MinaFoundation/mina repository
- [x] Lock mirror branches (develop, rampup, berkeley, compatible), allow Fork sync only
- [x] Set default branch to `mf-develop`

**Comment by kaozenn** [comment]
Completed. Will adjust the branching model if needed
