### ISSUE TITLE
Heavily comment the `integration_test_lib` and `test_executive`

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/mina#81]
**Problem**
There are _very few_ comments in the `integration_test_lib`. This makes the learning curve too steep.

**Assessment Criteria**
Commonly used testing functions will have numerous comments to aid test writers.

**Tasks**

- [ ] Add comments to `Intf` module values, types, modules, and signatures
- [ ] Add comments to `Dsl` module values, types, modules, and signatures
- [ ] Add comments to `Test_config` module values, types, modules, and signatures
- [ ] Add comments to `Malleable_error` module values, types, modules, and signatures
- [x] Add comments to `Test_common` module

**Comment by Isaac-DeFrain** [comment]
WIP PR for `Test_common` and integration test improvements https://github.com/MinaFoundation/mina/pull/18
