### ISSUE TITLE
Design New Test Executive

### ISSUE THREAD

**Issue by ejMina226** [MinaFoundation/mina#9]
**Problem**
We need to decide on how best refactor the Test Executive. This task is purely for the design, not the implementation.

**Acceptance Criteria**
At the end  of this task we should have a concrete vision for how best to design the new test executive and a set of GitHub tickets that can be picked up by a developer who can start coding them.

**Tasks**
The following requires:
- [x] Deciding on technologies for Test Executive and testing framework
- [x] Create centralised resource for design decisions (i.e. Notion page to invite feedback)
- [x] Collate feedback.
- [x] Decide on how to separate configuration from tests (e.g. functors, objects, etc).
- [x] Create GitHub tickets so that multiple people can pick up and start coding.

**Comment by ejMina226** [comment]
Due to the modularity of the Test_Executive (i.e. tests and engine), we just need to define a new engine.
